version: '3.7'
services:
  db:
    image: postgres:14-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playgroung_database
    ports:
      - '5432:5432'